// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2A2Glz2R8GhlfVLgKypSNxs5pszb_o2c',
    appId: '1:412187013024:web:f1b2227f62572934bd3ec5',
    messagingSenderId: '412187013024',
    projectId: 'staff-management-system-3a968',
    authDomain: 'staff-management-system-3a968.firebaseapp.com',
    storageBucket: 'staff-management-system-3a968.firebasestorage.app',
    measurementId: 'G-G35VE9L1T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCggq4nlkFsMYfM9HMh-WJkCvi3qxZL074',
    appId: '1:412187013024:android:3189b62e8b9a342ebd3ec5',
    messagingSenderId: '412187013024',
    projectId: 'staff-management-system-3a968',
    storageBucket: 'staff-management-system-3a968.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQmp4r8jmJ2HlhP6Jfb1bJ56sH-b_zzs',
    appId: '1:412187013024:ios:6f9293985c126749bd3ec5',
    messagingSenderId: '412187013024',
    projectId: 'staff-management-system-3a968',
    storageBucket: 'staff-management-system-3a968.firebasestorage.app',
    iosBundleId: 'com.example.labtestStaffSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuQmp4r8jmJ2HlhP6Jfb1bJ56sH-b_zzs',
    appId: '1:412187013024:ios:6f9293985c126749bd3ec5',
    messagingSenderId: '412187013024',
    projectId: 'staff-management-system-3a968',
    storageBucket: 'staff-management-system-3a968.firebasestorage.app',
    iosBundleId: 'com.example.labtestStaffSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2A2Glz2R8GhlfVLgKypSNxs5pszb_o2c',
    appId: '1:412187013024:web:56517fcd35cf656ebd3ec5',
    messagingSenderId: '412187013024',
    projectId: 'staff-management-system-3a968',
    authDomain: 'staff-management-system-3a968.firebaseapp.com',
    storageBucket: 'staff-management-system-3a968.firebasestorage.app',
    measurementId: 'G-ED16CLLYRC',
  );
}
